{
 "title": "Envoy Canary",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(sum(envoy_cluster_upstream_rq) by (kubernetes_namespace))"
   },
   {
    "name": "target",
    "label": "Target",
    "query": "query_result(sum(envoy_cluster_upstream_rq{kubernetes_namespace=\"$namespace\",envoy_cluster_name=~\".*-primary.*\"}) by (envoy_cluster_name))"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>RED: $target.$namespace</span>\n</div>"
  },
  {
   "title": "Primary: Incoming Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(rate(envoy_cluster_upstream_rq{kubernetes_namespace=~\"$namespace\",envoy_cluster_name=~\"$target-primary.*\"}[30s])), 0.001)"
    }
   ]
  },
  {
   "title": "Incoming Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq{kubernetes_namespace=~\"$namespace\",envoy_cluster_name=~\"$target-primary.*\",envoy_response_code!~\"5.*\"}[30s])) / sum(irate(envoy_cluster_upstream_rq{kubernetes_namespace=~\"$namespace\",envoy_cluster_name=~\"$target-primary.*\"}[30s]))"
    }
   ]
  },
  {
   "title": "Canary: Incoming Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(rate(envoy_cluster_upstream_rq{kubernetes_namespace=~\"$namespace\",envoy_cluster_name=~\"$target-canary.*\"}[30s])), 0.001)"
    }
   ]
  },
  {
   "title": "Incoming Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq{kubernetes_namespace=~\"$namespace\",envoy_cluster_name=~\"$target-canary.*\",envoy_response_code!~\"5.*\"}[30s])) / sum(irate(envoy_cluster_upstream_rq{kubernetes_namespace=~\"$namespace\",envoy_cluster_name=~\"$target-canary.*\"}[30s]))"
    }
   ]
  },
  {
   "title": "Primary: Incoming Traffic",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{kubernetes_namespace=~\"$namespace\",envoy_cluster_name=~\"$target-primary.*\"}[30s])))",
     "legendFormat": "traffic"
    }
   ]
  },
  {
   "title": "Canary: Incoming Traffic",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{kubernetes_namespace=~\"$namespace\",envoy_cluster_name=~\"$target-canary.*\"}[30s])))",
     "legendFormat": "traffic"
    }
   ]
  }
 ]
}