apiVersion: v1
kind: ConfigMap
metadata:
  name: flagger-grafana-providers
  namespace: projectcontour
data:
  providers.yaml: |+
    apiVersion: 1

    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /etc/grafana/dashboards
