apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/{{gitops.cluster.name}}/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
