app: imdb
containerArgs: []
environment: dev
image: ghcr.io/cse-labs/pib-imdb:latest
namespace: imdb
nodePort: 30080
port: 8080
targets:
    - region:central
    - ring:0
    - ring:1
template: pib-service
