---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/west-wa-sea-101/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
