apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.app}}-imdb
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.app}}-imdb
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: {{gitops.app}}-imdb
  template:
    metadata:
      labels:
        app: {{gitops.app}}-imdb
    spec:
      containers:
        - name: app
          image: {{gitops.image}}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            failureThreshold: 10
            periodSeconds: 60
          startupProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            failureThreshold: 60
            periodSeconds: 2
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          args:
          - --sleep
          - "5000"
          - --run-loop
          - --server
          - https://yourclustername.yourdomain.com
          - https://yourclustername.yourdomain.com
          - --files
          - imdb-load.json
          - --zone
          - {{gitops.cluster.zone}}
          - --region
          - {{gitops.cluster.region}}
          - --log-format
          - Json

---
apiVersion: v1
kind: Service
metadata:
  name: {{gitops.app}}-imdb
  namespace: {{gitops.namespace}}
  labels:
    app: {{gitops.app}}-imdb
spec:
  type: ClusterIP
  ports:
    - port: {{gitops.port}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{gitops.app}}-imdb
