apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/myapp/kic-deploy/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
