---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: redis
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/central-tx-hou-101/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
