apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{gitops.app}}
  namespace: {{gitops.namespace}}

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{gitops.app}}
  namespace: {{gitops.namespace}}
rules:
- apiGroups: [ "" ]
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{gitops.app}}
  namespace: {{gitops.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{gitops.app}}
subjects:
- kind: ServiceAccount
  name: {{gitops.app}}
  namespace: {{gitops.namespace}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{gitops.app}}-config
  namespace: {{gitops.namespace}}
  labels:
    k8s-app: {{gitops.app}}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output.conf
  output.conf: |
    [OUTPUT]
        Name              loki
        Match             kube.var.log.containers.webv*.*
        Host              {{gitops.lokiHost}}
        Port              443
        tls               on
        tls.verify        on
        http_user         {{gitops.lokiUser}}
        http_passwd       ${LOKI_PASSWORD}
        Labels            job=webv-{{gitops.jobSuffix}}
        label_keys        $StatusCode,$Server
        remove_keys       $StatusCode,$Server
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/webv*.log
        multiline.parser  docker, cri
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   Off
        Refresh_Interval  10
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Trim      On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         Off
        Labels              On
    [FILTER]
        Name          nest
        Match         kube.*
        Operation     lift
        Nested_under  kubernetes
        Add_prefix    kubernetes_
    [FILTER]
        Name          nest
        Match         kube.*
        Operation     lift
        Nested_under  kubernetes_labels
        Add_prefix    kubernetes_labels_
    [FILTER]
        Name type_converter
        Match kube.*
        int_key StatusCode status_str string
    [FILTER]
        Name                grep
        Match               kube.*
        Exclude             status_str /^2.*/

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{gitops.app}}
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.app}}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{gitops.app}}
  template:
    metadata:
      name: {{gitops.app}}
      labels:
        app.kubernetes.io/name: {{gitops.app}}
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: {{gitops.app}}
      terminationGracePeriodSeconds: 10
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{gitops.app}}
          imagePullPolicy: Always
          image: {{gitops.image}}
          env:
            - name: LOKI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fluent-bit-secrets
                  key: fluent-bit.key
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          volumeMounts:
          - name: varlog
            mountPath: /var/log

          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true

          - name: {{gitops.app}}-config
            mountPath: /fluent-bit/etc/

      volumes:
        - name: varlog
          hostPath:
            path: /var/log

        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers

        - name: {{gitops.app}}-config
          configMap:
            name: fluent-bit-config
