apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:

        - name: redis
          image: redis
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 6379
              protocol: TCP

          volumeMounts:
            - name: redis-vol
              mountPath: /data

          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
      volumes:
        - name: redis-vol
          persistentVolumeClaim:
            claimName: redis-pvc

          # readinessProbe:
          #   initialDelaySeconds: 5
          #   failureThreshold: 60
          #   periodSeconds: 2
          #   httpGet:
          #     path: /readyz
          #     port: 8080

          # livenessProbe:
          #   initialDelaySeconds: 60
          #   periodSeconds: 60
          #   httpGet:
          #     path: /healthz
          #     port: 8080
