apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{gitops.app}}-ingress
  namespace: {{gitops.app}}
spec:
  virtualhost:
    fqdn: 20.150.157.24/{{gitops.ingressPrefix}}
  includes:
    - name: {{gitops.app}}
      namespace: {{gitops.app}}
