apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pvc.yaml
- cvcapture.yaml
- inference.yaml
- predict.yaml
- rtspsim.yaml
- upload.yaml
- web.yaml
- ingress{{gitops.cluster.ingressType}}.yaml
