app: skumanager
containerArgs: []
cpuLimit: 2000m
cpuRequest: 1000m
environment: dev
image: ghcr.io/cse-labs/skumanager:beta
ingressPrefix: /
livenessProbe: /version
memoryLimit: 2048Mi
memoryRequest: 1024Mi
namespace: skumanager
nodePort: 30080
port: 8080
readinessProbe: /version
targets: []
template: pib-service
