app: dogs-cats
containerArgs: []
environment: dev
image: ghcr.io/cse-labs/go-vote:latest
key1: Dogs
key2: Cats
namespace: dogs-cats
nodePort: 30080
port: 8080
targets: []
template: vote-service
title: Dogs Rule!
