apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: imdb-ingress
  namespace: imdb
spec:
  virtualhost:
    fqdn: 20.169.44.36
  includes:
    - name: imdb
      namespace: imdb
      conditions:
      - prefix: /
    - name: flagger-grafana
      namespace: projectcontour
      conditions:
      - prefix: /grafana
  # routes:
  # - services:
  #   - name: imdb
  #     port: 80
  #   conditions:
  #     - prefix: /
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: flagger-grafana
  namespace: projectcontour
spec:
  routes:
    - services:
        - name: flagger-grafana
          port: 80
      conditions:
        - prefix: /grafana
