{
 "title": "%%FLEET_NAME%% Fleet",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "apps",
    "label": "App",
    "query": {
     "query": "label_values(WebVSummary{origin_prometheus=\"monitoring-%%FLEET_NAME%%\"}, job)"
    }
   },
   {
    "name": "regions",
    "label": "Regions",
    "query": {
     "query": "label_values(WebVSummary{origin_prometheus=\"monitoring-%%FLEET_NAME%%\",job=\"$apps\"}, server)"
    }
   },
   {
    "name": "servers",
    "label": "Stores",
    "query": {
     "query": "label_values(WebVSummary{origin_prometheus=\"monitoring-%%FLEET_NAME%%\", job=\"$apps\"}, server)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (server_region)( label_replace(\r\ncount(\r\n(sum by (server)(rate(WebVDuration_count{origin_prometheus=\"monitoring-%%FLEET_NAME%%\",job=\"$apps\",status=\"OK\",server=~\".*$regions.*\"}[1m]) or WebVDuration_count{origin_prometheus=\"monitoring-%%FLEET_NAME%%\",job=\"$apps\",server=~\"$servers\"}*0 ) / sum by (server) (rate(WebVDuration_count{origin_prometheus=\"monitoring-%%FLEET_NAME%%\",job=\"$apps\"}[1m])) * 100)>90) by (server), \"server_region\", \"$1\", \"server\", \"^........([a-z]*)-[a-z]*-[a-z]*-.*.%%DOMAIN_NAME%%\")) ",
     "legendFormat": "{{server_region}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(sum by (server) (rate(WebVDuration_count{origin_prometheus=\"monitoring-%%FLEET_NAME%%\",job=\"$apps\",status=\"OK\",server=~\"$servers\",server=~\".*$regions.*\"}[1m]) or WebVDuration_count{origin_prometheus=\"monitoring-%%FLEET_NAME%%\",job=\"$apps\",server=~\"$servers\"}*0) / sum(rate(WebVDuration_count{origin_prometheus=\"monitoring-%%FLEET_NAME%%\",job=\"$apps\",server=~\"$servers\",server=~\".*$regions.*\"}[1m])) by (server) * 100, \"server_name\", \"$1\", \"server\", \"^........([a-z]*-[a-z]*-[a-z]*-.*).%%DOMAIN_NAME%%\")",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "P95 Response Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WebVSummary{origin_prometheus=\"monitoring-%%FLEET_NAME%%\",job=\"$apps\",quantile=\"0.95\",status=\"OK\",server=~\"$servers\",server=~\".*$regions.*\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "targets": [
    { "expr": "rate(WebVDuration_count[5m])" }
   ]
  },
  {
   "title": "Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(WebVSummary_count{origin_prometheus=\"monitoring-%%FLEET_NAME%%\",job=\"$apps\",status=\"OK\",server=~\"$servers\",server=~\".*$regions.*\"}[1m])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Errors / min",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"webv-%%FLEET_NAME%%\",StatusCode!=\"200\"}|~\"$apps\"|Server=~\".*($regions).*\"|Server=~\"$servers\"|Server!=\"\"[1m])) by (Server)",
     "legendFormat": "{{Server}}"
    }
   ]
  },
  {
   "title": "P95 Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "WebVSummary{origin_prometheus=\"monitoring-%%FLEET_NAME%%\",job=\"$apps\",quantile=\"0.95\",status=\"OK\",server=~\"$servers\",server=~\".*$regions.*\"}",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}