# source: https://github.com/fluxcd/flagger/tree/main/kustomize/contour
namespace: projectcontour
commonLabels:
  app: flagger
resources:
  - account.yaml
  - rbac.yaml
  - crd.yaml
  - deployment.yaml
  - flagger-prometheus.yaml
images:
  - name: ghcr.io/fluxcd/flagger
    newName: ghcr.io/fluxcd/flagger
    newTag: 1.22.1
configMapGenerator:
  - name: flagger-prometheus
    files:
      - prometheus.yml
