apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/west-wa-bartr-1001/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
