apiVersion: v1
kind: ConfigMap
metadata:
  name: {{gitops.app}}-datasources
  namespace: {{gitops.namespace}}
data:
  datasources.yaml: |-
    apiVersion: 1

    deleteDatasources:
      - name: prometheus
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://flagger-prometheus:9090
      isDefault: true
      editable: true
      version: 1
