apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{gitops.app}}-ingress
  namespace: {{gitops.namespace}}
spec:
  virtualhost:
    fqdn: {{gitops.cluster.domain}}
  includes:
    - name: {{gitops.app}}
      namespace: {{gitops.namespace}}
  routes:
    - conditions:
      - prefix: /
        services:
      - name: {{gitops.app}}
        port: 80
