apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{gitops.app}}-ingress
  namespace: {{gitops.namespace}}
spec:
  virtualhost:
    fqdn: {{gitops.cluster.domain}}
  includes:
    - name: {{gitops.app}}
      namespace: {{gitops.namespace}}
      conditions:
      - prefix: /
    - name: flagger-grafana
      namespace: projectcontour
      conditions:
      - prefix: /grafana
---

apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: flagger-grafana
  namespace: projectcontour
spec:
  routes:
    - services:
        - name: flagger-grafana
          port: 8080
