apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{gitops.app}}-ingress
  namespace: {{gitops.namespace}}
spec:
  virtualhost:
    fqdn: {{gitops.cluster.domain}}
  includes:
    - name: {{gitops.app}}
      namespace: {{gitops.namespace}}
  routes:
  - services:
    - name: {{gitops.app}}
      port: 8080
    conditions:
      - prefix: /
  - services:
    - name: projectcontour/flagger-grafana
      port: 8080
    conditions:
      - prefix: /grafana
