#!/bin/bash

if [ "$1" = "" ]
then
    echo "Error: /path is required"
    echo "usage: flt curl /path"
else
    if [ "$PIB_SSL" = "" ]
    then
        curl -s http://localhost$1
    else
        curl -s https://"$PIB_FQDN$1"
    fi
fi
