#!/bin/zsh
echo "$(date +'%Y-%m-%d %H:%M:%S')  patched" >> /home/pib/status

env | grep PIB
# docker pull ghcr.io/cse-labs/pib-webv:latest
# docker pull ghcr.io/cse-labs/pib-webv:beta

echo "$(hostname) patched"
