#!/bin/bash

tag=$1

mkdir -p "$HOME/bin"
# update CLI
cd "$HOME/bin" || exit

# remove old CLI
rm -rf kic .kic

if [ "$tag" = "" ]; then
    # use latest release
    tag=$(curl -s https://api.github.com/repos/microsoft/pilot-in-a-box/releases/latest | grep tag_name | cut -d '"' -f4)
fi

wget -O vm-kic.tar.gz "https://github.com/microsoft/pilot-in-a-box/releases/download/$tag/vm-kic-$tag-linux-amd64.tar.gz"
tar -xvzf vm-kic.tar.gz
rm vm-kic.tar.gz

cd "$OLDPWD" || exit
