#!/bin/bash

tag=$1

mkdir -p "$HOME/bin"
# update CLI
cd "$HOME/bin" || exit

# remove old CLI
rm -rf kic .kic

if [ "$tag" = "" ]; then
    # use latest release
    tag=$(curl -s https://api.github.com/repos/kubernetes101/pib-dev/releases/latest | grep tag_name | cut -d '"' -f4)
fi

wget -O kic.tar.gz "https://github.com/kubernetes101/pib-dev/releases/download/$tag/kic-$tag-linux-amd64.tar.gz"
tar -xvzf kic.tar.gz
rm kic.tar.gz

cd "$OLDPWD" || exit
