apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - fluentbit/account.yaml
  - fluentbit/daemonset.yaml
  - fluentbit/log.yaml
  - fluentbit/stdout-config.yaml
  - prometheus/1-clusterRole.yaml
  - prometheus/2-config-map.yaml
  - prometheus/3-prometheus-deployment.yaml
  - grafana/dashboard-provider.yaml
  - grafana/datasource.yaml
  - grafana/deployment.yaml
  - grafana/dashboards/app.yaml
  - grafana/dashboards/dotnet.yaml
